/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Kingston
 */
//Generated by GuiGenie - Copyright (c) 2004 Mario Awad.
//Home Page http://guigenie.cjb.net - Check often for new versions!

import controller.Controller;
import java.awt.*;
import java.awt.event.*;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.nio.charset.Charset;
import java.nio.file.Files;
import java.nio.file.Path;
import javax.swing.*;
import javax.swing.event.*;

public class EditFrame extends JPanel {
    private JButton saveBtn;
    private JTextArea editTextArea;
    private JButton cancelBtn;
    private final JScrollPane scroll;
    private Controller c;

    public EditFrame(File file, String contents, Controller c) {
        this.c = c;
        //construct components
        saveBtn = new JButton ("Save");
        editTextArea = new JTextArea (10, 10);
        cancelBtn = new JButton ("Cancel");
        
        scroll = new JScrollPane(editTextArea, JScrollPane.VERTICAL_SCROLLBAR_ALWAYS, JScrollPane.HORIZONTAL_SCROLLBAR_ALWAYS);

        editTextArea.setLineWrap(true);
        editTextArea.setWrapStyleWord(true);

        //adjust size and set layout
        setPreferredSize (new Dimension (784, 513));
        setLayout (null);
        scroll.setSize( 784, 400 );

        //add components
        add (saveBtn);
        add (scroll);
        //add (cancelBtn);

        //set component bounds (only needed by Absolute Positioning)
        saveBtn.setBounds (650, 460, 125, 35);
        editTextArea.setBounds (15, 15, 755, 430);
        cancelBtn.setBounds (510, 460, 125, 35);
        
        editTextArea.setText(contents);
        
    saveBtn.addActionListener((ActionEvent e) ->
        {
            try {
                
                // if file doesnt exists, then create it
                if (!file.exists()) {
                    file.createNewFile();
                }
                
                FileWriter fw = new FileWriter(file.getAbsoluteFile());
                try (BufferedWriter bw = new BufferedWriter(fw))
                {
                    bw.write(editTextArea.getText());
                }
                
                System.out.println("Done");
                
            } catch (IOException ex) {
            }
        });
    }
    

}

